### ISSUE TITLE
3d secure

### ISSUE THREAD

**Issue by PhenomAmd** [PagoFacil/MagentoPlugin#6]
se puede saber que diablos les pasa primeramente sus tutoriales de instalacion en la pagina estan desactualizados estuve una maldita hora figurandome que estaba haciendo mal hasta que salen con que actualizaron sin decirle nada a la gente que somos sus clientes no obstante a esto ahora remueven el 3D Secure del modulo dejanos desprotegidos de todos los malditos niños rata que hay alla afuera para que alrato cuando vendamos y contracarguen ustedes salgan con sus tonterias de "lamentablemente necesitamos 90/60 dias para poder saber mas al respecto" no se ustedes pero muchos de nosotros no tenemos una empresa que cobra por cobrar y no me puedo dar el lujo de perder mercancia/dinero solo porque ustedes decidieron quitar la opcion

**Comment by mikepago** [comment]
Hola buen día

El 3dsecure no se ha quitado, puede enviarnos sus datos de cliente al correo info@pagofacil.net para darle seguimiento a su caso por favor.

Saludos.

**Comment by PhenomAmd** [comment]
El problema aqui es que ni siquiera es la version oficial de este repositorio la que funciona correctamentr no obstante la version descargable en tu pagina tampoco sirve y me doy cuenta que cierras el problema para evitar posts de los demas reclamando lo mismo se supone que la comunidad github es de COLABORACION y no escribire un correo ya que la ultima vez incluso un amigo mio descubrio los datos dd acceso a su base de datos por error y no fueron ni para ayudarlo encima le contestaron cuando se les dio la gana yo por confiar nuevamente en ustedes aqui estuve sufriendoas alrato pongo post del repositorio que funciona correctamente con magento 1.9.4 php7.2 sin sus tonterias de usar mcrypt
